# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32dce8409e660391f9d25b68a2c21318b1c480e8b025fdb9a6324d43989fbd4d458c9b7cb22a81dbc51805d9f29da64e03a43e9a44bb4852780e086058e69e05

test:
  secret_key_base: 426eeaf92499677e48fa02687d8fddf9d4f6016042644cec90f490cf002ae1318267ca3fc27bf1c7ed72838a36a4ccad0c59b2fea5844459665e51528714d788

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
